Wands
mcstepp/enchanted pull request #70
Opened 2021-08-28 16:02 UTC by tiny-trevor

- When you create a pending character, you can pick a wand from a given list of woods, cores and lengths
- When your character is accepted, if they're not a Squib or Muggle, the wand is created for that character
-- may need some revision/neatening up

2022-01-30 11:22 UTC, jvn145 requested changes
Missing tests - should be a quick one, just adding wands to character tests (and maybe a "a squib can't have a wand test"? or something similar to test that conditional logic in the character controller?

2022-01-30 11:22 UTC, jvn145 commented on resources/js/components/WandSelectorComponent.vue
> +      for(let i = 5.00; i <= 20.00; i++) {
bit short for a wand - the shortest want I can find is 10.5, scrolling through so much is a little annoying

```suggestion
      for(let i = 10.00; i <= 20.00; i++) {
```

2022-01-31 19:26 UTC, tiny-trevor commented
@jvn145 I have refined the wand creation in order to avoid squibs/muggles getting wands. I have also added two small tests to affirm this.

2022-02-03 18:54 UTC, jvn145 requested changes

2022-02-03 18:54 UTC, jvn145 commented on resources/js/components/WandSelectorComponent.vue
> +      );
should it not be the opposite? if they are either a squib or a muggle they are not magical

2022-02-03 18:54 UTC, jvn145 commented on resources/js/components/WandSelectorComponent.vue
> +        this.selected_length = '';
I agree that these should be disabled, however it would be annoying if you accidentally changed the character to squib/muggle and then had to reset these. It's a minor thing really but would be nice if either these just don't get passed on when the request is submitted or ignored by the controller if the character is not magical.

2022-02-03 18:54 UTC, jvn145 commented on tests/Unit/CharacterWandTest.php
> +        ]);
is the dorm required for wands?

2022-02-05 10:57 UTC, tiny-trevor commented on resources/js/components/WandSelectorComponent.vue
> +        this.selected_length = '';
Agreed, plus disabled fields don't get passed as part of the request, so no issues in just disabling the selections. 
Done

2022-02-05 10:58 UTC, tiny-trevor commented on resources/js/components/WandSelectorComponent.vue
> +      );
Done, changed to is_not_magical, thanks!

2022-02-05 10:59 UTC, tiny-trevor commented on tests/Unit/CharacterWandTest.php
> +        ]);
The dorm is required for the form, if the character is a student. The factory doesn't pre-populate because it could make a graduate character.

2022-02-05 11:25 UTC, jvn145 approved these changes

2022-02-12 22:34 UTC, merged